[build]
  publish = "."
  command = ""

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-store"

# Ensure correct MIME types for JS modules (not strictly needed here, but safe defaults)
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

# Security and permissions
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
